###

POST http://127.0.0.1:5000/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Apólice - Renovação Frota Rod Transportes - Auto.pdf"
Content-Type: application/pdf

< I:\Meu Drive\FROTAS\CAMILA\MINHAS FROTAS\ROD\2025-2026\AUTO\APÓLICE - RENOVAÇÃO FROTA ROD TRANSPORTES - AUTO.pdf
--WebAppBoundary--
